alias PiMS_up="docker-compose -f ~/PiMS/docker-compose.yml up -d"
alias PiMS_down="docker-compose -f ~/PiMS/docker-compose.yml down"
alias PiMS_start="docker-compose -f ~/PiMS/docker-compose.yml start"
alias PiMS_stop="docker-compose -f ~/PiMS/docker-compose.yml stop"
alias PiMS_update="docker-compose -f ~/PiMS/docker-compose.yml pull"
alias PiMS_build="docker-compose -f ~/PiMS/docker-compose.yml build"
