  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - /media/USB_PLEX_14TB/TV:/tv
      - /media/USB_PLEX_14TB/DOWNLOADS:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
