  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/lidarr/config:/config
      - /media/USB_PLEX_14TB/MUSIC:/music
      - /media/USB_PLEX_14TB/DOWNLOADS:/downloads
    ports:
      - 8686:8686
