  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/emby/config:/config
      - /media/USB_PLEX_14TB/tvshows:/data/tvshows
      - /media/USB_PLEX_14TB/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
