  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/emby/config:/config
      - /media/usb_ELEMENT2TB/DOWNLOADS/tvshows:/data/tvshows
      - /media/usb_ELEMENT2TB/DOWNLOADS/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
