  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - /media/usb_ELEMENT2TB/DOWNLOADS:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
