# ==================================================================================================================================
# homeassistant yml
# ==================================================================================================================================
  homeassistant:
    image: "homeassistant/raspberrypi4-homeassistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/homeassistant/addons:/homeassistant/addons"
      - "./volumes/homeassistant/conf:/homeassistant/conf"
      - "./volumes/homeassistant/userdata:/homeassistant/userdata"
    environment:
      homeassistant_HTTP_PORT: "8080"
      homeassistant_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/London"
#    # The command node is very important. It overrides
#    # the "gosu homeassistant tini -s ./start.sh" command from Dockerfile and runs as root!
#    command: "tini -s ./start.sh server"