# ==================================================================================================================================
# homeassistant yml
# ==================================================================================================================================
  homeassistant:
    image: "homeassistant/raspberrypi4-homeassistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volumes/homeassistant/addons:/homeassistant/addons
      - ./volumes/homeassistant/conf:/homeassistant/conf
      - ./volumes/homeassistant/userdata:/homeassistant/userdata
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
