  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - ./media/usb_ELEMENT2TB/DOWNLOADS/movies:/movies
      - ./media/usb_ELEMENT2TB/DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
